name: Checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  checks: write
jobs:
  Checks-JS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get tags
        run: git fetch --tags origin
      - run: git describe --abbrev=0 --tags
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.7.2
      - name: Run Js tests
        run: ./gradlew jsBrowserTest --warn --continue
      - name: Run Wasm tests
        run: ./gradlew wasmJsBrowserTest --warn --continue
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'
          check_name: 'JS JUnit Test Report'
          require_tests: true
  Checks-Jvm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get tags
        run: git fetch --tags origin
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'
      - name: Run Android tests
        run: ./gradlew :library:testDebugUnitTest --warn --continue
      - name: Run Jvm tests
        run: ./gradlew :library:jvmTest --warn --continue
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'
          check_name: 'JVM JUnit Test Report'
          require_tests: true
  Checks-Apple:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get tags
        run: git fetch --tags origin
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'
      - name: Run Apple tests
        run: ./gradlew :library:iosSimulatorArm64Test --warn --continue
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'
          check_name: 'Apple JUnit Test Report'
          require_tests: true