name: Checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Checks-JS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.7.2

      - name: Run Js tests
        run: ./gradlew jsBrowserTest --warn
      - name: Run Wasm tests
        run: ./gradlew wasmJsBrowserTest --warn
  Checks-Jvm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'
      - name: Run Android tests
        run: ./gradlew :library:testDebugUnitTest --warn --continue
      - name: Run Jvm tests
        run: ./gradlew :library:jvmTest --warn --continue
  Checks-Apple:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'
      - name: Run Apple tests
        run: ./gradlew :library:iosSimulatorArm64Test --warn --continue